import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { FaDiscord } from "react-icons/fa";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main>Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-4">
        <h1 className="mt-12 tracking-tight sm:text-[4rem]">Twitter Clone</h1>
        <aside className="pt-10">
          {session ? (
            <>
              <p>Welcome, {session.user?.name}</p>
              <button
                onClick={() => signOut()}
                type="button"
                className="mr-2 mb-2 rounded-lg bg-red-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300"
              >
                <span className="flex items-center gap-2">Log Out</span>
              </button>
            </>
          ) : (
            <button
              onClick={() => signIn("discord")}
              type="button"
              className="mr-2 mb-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300"
            >
              <span className="flex items-center gap-2">
                <FaDiscord /> Login
              </span>
            </button>
          )}
        </aside>
      </main>
    </>
  );
};

export default Home;
