import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { FaDiscord } from "react-icons/fa";
import { Timeline } from "../components/Timeline";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main>Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className="m-4 text-center">
          <h1 className="mt-12 text-[4rem] font-bold tracking-tight text-sky-500">
            Twitter
          </h1>
          <aside className="pt-8">
            {session ? (
              <>
                <p>Welcomes you, {session.user?.name}</p>
                <button
                  onClick={() => signOut()}
                  type="button"
                  className="fixed right-4 top-4 mr-2 mb-2 rounded-lg bg-red-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300"
                >
                  <span className="flex items-center gap-2">Log Out</span>
                </button>
                <Timeline where={undefined} />
              </>
            ) : (
              <button
                onClick={() => signIn("discord")}
                type="button"
                className="mr-2 mb-2 rounded-lg bg-slate-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-slate-800 focus:outline-none focus:ring-4 focus:ring-slate-300"
              >
                <span className="flex items-center gap-2">
                  <FaDiscord /> Login
                </span>
              </button>
            )}
          </aside>
        </main>{" "}
      </div>
    </>
  );
};

export default Home;
